version: '3'

services:
  app:
    image: docker-market-nextjs
    build: .
    ports:
      - 80:3000
    volumes: 
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles